name: Make draft release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Define version env variable
        run: |
          echo "VERSION=$(grep \"version = \" build.gradle | sed -E -e 's/\s+version\s+=\s+//' | sed -E -e 's/\"\'//g'" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: build -Pversion=$VERSION

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --draft ${{ github.ref_name }} --title ${{ github.ref_name }} build/libs/*
